#!/usr/bin/python3
# Launches the application that a .desktop file represents, passing in any
# provided arguments. This is to work around the fact that xdg opens
# desktop files as if they are text files.

from gi.repository import Gio
import sys

if len(sys.argv) < 2:
    print("Usage:", sys.argv[0], "file.desktop <arg1> <arg2> ...")
else:
    Gio.DesktopAppInfo.new_from_filename(sys.argv[1]).launch_uris(sys.argv[2:])
