#!/bin/bash

if [ -z "$1" ]; then
        exec 1>&2
	echo Usage: $0 c-file
	exit 1
fi

if [ -f /tmp/runc-exec ]; then
	rm /tmp/runc-exec
fi

gcc "$1" --std=c99 -O2 -o/tmp/runc-exec
shift

if [ -f /tmp/runc-exec ]; then
	/tmp/runc-exec "$@"
fi


